### ISSUE TITLE
HTTP Validation failed

### ISSUE THREAD

**Issue by filiptronicek** [JasonEtco/activity-box#14]
My action generated from the template suddenly stopped working and spitting out this error: (see logs [here](https://pipelines.actions.githubusercontent.com/cXV8n9Y6tJH3BaBp7A1yb3hO5H63XGUxoijUhhlBYOcZiRUAHD/_apis/pipelines/1/runs/3064/signedlogcontent/3?urlExpires=2020-06-22T18%3A29%3A47.0237133Z&urlSigningMethod=HMACV1&urlSignature=5hjDvHKaG6T0KpV%2Fr%2BD3akLHu10fWSWi3sATOBvjH3s%3D))

`
2020-06-22T18:28:19.1126179Z ⬤  debug     Getting activity for filiptronicek
2020-06-22T18:28:19.6148552Z ⬤  debug     Activity for filiptronicek, 100 events found.
2020-06-22T18:28:19.6152187Z ⬤  debug     Updating Gist 4bd350ff9bc3244caefefab69e263bfa
2020-06-22T18:28:24.3806716Z ⬤  debug     Error getting or update the Gist:
2020-06-22T18:28:24.3818817Z ✖  fatal     HttpError: Validation Failed: {"resource":"Gist","code":"missing_field","field":"files"} 
2020-06-22T18:28:24.3819586Z     at /node_modules/@octokit/request/dist-node/index.js:66:23
2020-06-22T18:28:24.3819890Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-06-22T18:28:24.3820291Z     at async Toolkit.run.event (/index.js:59:7)
2020-06-22T18:28:24.5616307Z Cleaning up orphan processes
`

**Comment by filiptronicek** [comment]
Now build correctly, just has a weird name...
![image](https://user-images.githubusercontent.com/29888641/85323575-840b1880-b4c8-11ea-8915-ec3f36a72122.png)

**Comment by HPaulson** [comment]
> 
> 
> Now built correctly, just has a weird name...
@filiptronicek 

You can change the name of a gist manually, the action should have no effect on the name of the gist.

**Comment by filiptronicek** [comment]
> > 
> 
> > 
> 
> > Now built correctly, just has a weird name...
> 
> @filiptronicek 
> 
> 
> 
> You can change the name of a gist manually, the action should have no effect on the name of the gist.
> 
> 

Weird that it still changed the name by itself....

**Comment by HPaulson** [comment]
Is this still occurring? Have you tried changing the name to something and running it to see if it changes again? @filiptronicek

**Comment by filiptronicek** [comment]
> Is this still occurring? Have you tried changing the name to something and running it to see if it changes again? @filiptronicek 

It's not occurring anymore, but just something to note, perhaps was a GitHub actions issue, who knows...
